
import Link from 'next/link';
import { getAllPostIds, getPostData } from '../../lib/posts';
import Head from 'next/head'
import Navbar from '@/components/navbar';
import SingleProject from '@/components/singleproject';
import projects from '../../data/projects'
import path from 'path'
import matter from 'gray-matter'

// export async function getStaticProps({ params }) {
//   try {
//     const postData = getPostData(params.id);
//     return {
//       props: {
//         postData,
//       },
//     };
//   } catch (error) {
//     console.log(error);
//     return {
//       props: {
//         postData: null,
//       },
//     };
//   }
// }

export async function getServerSideProps({ params }) {
  try {
    const project = projects.find((project) => project.id.toString() === params.id);
    const matterResult = matter(project.description);

    return {
      props: {
        postData: {
          id: params.id,
          ...project,
          content: matterResult.content,
        },
      },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {
        postData: null,
      },
    };
  }
}




export default function Post({ postData }) {
  return (
    <>
      <Head>
        <title>Site - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <Navbar/>
      <SingleProject event={postData}/>
    </>
  );
}


// export async function getStaticPaths() {
//   const paths = getAllPostIds();
//   return {
//     paths,
//     fallback: false,
//   };
// }